# Generated by Django 3.0.5 on 2020-04-13 01:26

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=256)),
                ('phone_number', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=256)),
                ('date_text_sent', models.DateTimeField(null=True)),
                ('date_used', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raw_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('invitation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.SurveyInvitation')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('phone_number', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=256)),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.SurveyResponse')),
            ],
        ),
    ]
